version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Rogalik2016"
      POSTGRES_DB: "Books"
    networks:
      - dockerapi-dev 

  booksstore:
    image: ksenyarogaleva/booksstore:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"     
    networks:
      - dockerapi-dev  
  
   
volumes:
  db_volume:


